### ISSUE TITLE
Wrong payload in ResourceUnavailableMessage

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-Connector-Framework#20]
Used Framework v4.0.3: The connector successfully registeres a resource at the IDS broker, but is not able to remove it again. Error from the lab broker: `Could not extract class of child object`.

The multipart message built in `IDSBrokerServiceImpl::removeResourceFromBroker` adds an `ids:resource` as payload. The message's [documentation](http://htmlpreview.github.io/?https://github.com/IndustrialDataSpace/InformationModel/blob/feature/message_taxonomy_description/model/communication/Message_Description.htm) does not indicate that the `ResourceUnavailableMessage` should have a payload. According to @maboeckmann, this causes the error in the broker. His assumption on this: "XXXUnavailableMessage sollte keinen Payload haben - das gilt für Connector, Resource und auch sonstiges". Means, the payload should be `null`. 

Correspondingly, the `ConnectorUpdateMessage` would also have to be checked. However, this works despite the payload.

**Comment by tmberthold** [comment]
Thanks for the feedback, will take a look.

**Comment by tmberthold** [comment]
Will be addressed together with https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/84

**Comment by tmberthold** [comment]
Should be fixed in the IDS-Messaging-Services, we will also see what can be done here.

https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/issues/125

**Comment by tmberthold** [comment]
Status Update: Will be fixed for both supported versions.
- Version 5 (5.0.1): Fix-PullRequest https://github.com/International-Data-Spaces-Association/IDS-Connector-Framework/pull/32
- Version 4 (4.0.8): Fix-PullRequest https://github.com/International-Data-Spaces-Association/IDS-Connector-Framework/pull/33

**Comment by tmberthold** [comment]
The released new versions 5.0.1 & 4.0.8 (LTS v4) include the fix.

Note: For communication to the broker without resources, the connector config-json should have an empty ResourceCatalog.
